Update start-openvpn-admin to use bash-commons

diff --git a/modules/start-openvpn-admin/bin/run-process-requests b/modules/start-openvpn-admin/bin/run-process-requests
--- a/modules/start-openvpn-admin/bin/run-process-requests
+++ b/modules/start-openvpn-admin/bin/run-process-requests
@@ -11,8 +11,15 @@ readonly SUPERVISOR_CONFIG_PATH="/etc/supervisor/conf.d/openvpn-admin-requests.c
 readonly BIN_FULL_PATH="/usr/local/bin/openvpn-admin"
 readonly BIN_NAME="openvpn-admin"
 readonly LOG_DIR="/var/log"
+readonly BASH_COMMONS_DIR="/opt/gruntwork/bash-commons"
 
-readonly EMPTY_VAL="__EMPTY__"
+if [[ ! -d "$BASH_COMMONS_DIR" ]]; then
+  echo "ERROR: this script requires that bash-commons is installed in $BASH_COMMONS_DIR. See https://github.com/gruntwork-io/bash-commons for more info."
+  exit 1
+fi
+
+source "$BASH_COMMONS_DIR/log.sh"
+source "$BASH_COMMONS_DIR/assert.sh"
 
 function print_usage {
   echo
@@ -35,70 +42,9 @@ function print_usage {
   echo "     --syslog"
 }
 
-function log {
-  local readonly level="$1"
-  local readonly message="$2"
-  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-  local readonly script_name="$(basename "$0")"
-
-  >&2 echo -e "${timestamp} [${level}] [$script_name] ${message}"
-}
-
-function log_info {
-  local readonly message="$1"
-  log "INFO" "$message"
-}
-
-function log_warn {
-  local readonly message="$1"
-  log "WARN" "$message"
-}
-
-function log_error {
-  local readonly message="$1"
-  log "ERROR" "$message"
-}
-
 # Assert that this script is being run on an EC2 Instance
 function assert_is_ec2_instance {
   curl --silent -o /dev/null --fail "http://169.254.169.254/latest/meta-data/" && :
-}
-
-# Assert that we're running as the root user
-function assert_uid_is_root_or_sudo {
-  if [[ $EUID != 0 ]]; then
-    log_error "This script should be run using sudo or as the root user"
-    exit 1
-  fi
-}
-
-# Assert that the given argument is not empty
-function assert_not_empty {
-  local readonly arg_name="$1"
-  local readonly arg_value="$2"
-
-  if [[ -z "$arg_value" ]] || [[ "$arg_value" == "$EMPTY_VAL" ]]; then
-    log "ERROR: The value for '$arg_name' cannot be empty"
-    print_usage
-    exit 1
-  fi
-}
-
-# Assert that a given binary is installed on this box
-function assert_is_installed {
-  local readonly name="$1"
-
-  if [[ ! $(command -v ${name}) ]]; then
-    log_error "The binary '$name' is required by this script but is not installed or in the system's PATH."
-    exit 1
-  fi
-}
-
-# Based on http://unix.stackexchange.com/a/144330/129208
-function trim_last_character {
-  local readonly str="$1"
-
-  echo ${str::-1}
 }
 
 function generate_supervisor_config {
